# Generated by Django 4.1.4 on 2023-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slimstarg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stargentertainment',
            name='email',
        ),
        migrations.AddField(
            model_name='stargentertainment',
            name='event',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
