# Generated by Django 4.1.4 on 2023-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slimstarg', '0002_remove_stargentertainment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargentertainment',
            name='options',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=200),
        ),
    ]
