# Generated by Django 4.1.4 on 2023-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slimstarg', '0003_alter_stargentertainment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='stargentertainment',
            name='options',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=200),
        ),
    ]
