# Generated by Django 4.1.4 on 2023-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slimstarg', '0004_section_alter_stargentertainment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargentertainment',
            name='options',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=200),
        ),
    ]
